-- ============================================================
-- MANDALA TASKS TABLE
-- File: sql/mandala-tasks.sql
-- Run in Supabase SQL Editor
--
-- Stores tenant-aware task objects for the Mandala Task Engine.
-- Tasks are the unit of work: outreach, follow_up, rescue,
-- inbound_response, qualification.
-- ============================================================

CREATE TABLE IF NOT EXISTS mandala_tasks (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id               text NOT NULL,

  -- Task definition
  type                    text NOT NULL
                            CHECK (type IN ('outreach','follow_up','rescue','inbound_response','qualification')),
  objective               text NOT NULL,
  target                  jsonb NOT NULL,       -- { customer_number, customer_name?, conversation_id?, channel }
  context                 text NOT NULL DEFAULT '',
  constraints             jsonb NOT NULL DEFAULT '{}',  -- { max_messages, forbidden_topics, no_pricing, tone, language }
  approval_mode           text NOT NULL DEFAULT 'draft_only'
                            CHECK (approval_mode IN ('draft_only','semi_auto','fully_auto')),

  -- Lifecycle
  status                  text NOT NULL DEFAULT 'pending'
                            CHECK (status IN ('pending','in_progress','awaiting_review','approved','executed','failed','cancelled')),
  drafts                  jsonb NOT NULL DEFAULT '[]',  -- TaskDraft[] generated by AI
  log                     jsonb NOT NULL DEFAULT '[]',  -- TaskLogEntry[] execution audit trail
  result_conversation_id  uuid,                          -- FK to mandala_conversations (set after execution)
  error                   text,                          -- Error message if status = 'failed'

  -- Metadata
  created_by              text NOT NULL DEFAULT 'api',
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now(),
  executed_at             timestamptz
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_mt_tenant_status
  ON mandala_tasks(tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_mt_tenant_created
  ON mandala_tasks(tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mt_type
  ON mandala_tasks(type);
CREATE INDEX IF NOT EXISTS idx_mt_result_conv
  ON mandala_tasks(result_conversation_id)
  WHERE result_conversation_id IS NOT NULL;

-- RLS
ALTER TABLE mandala_tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_full_access_mt" ON mandala_tasks
  FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "authenticated_read_mt" ON mandala_tasks
  FOR SELECT TO authenticated USING (true);

-- Auto-update updated_at
DROP TRIGGER IF EXISTS update_mt_updated_at ON mandala_tasks;
CREATE TRIGGER update_mt_updated_at BEFORE UPDATE ON mandala_tasks
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
SELECT 'mandala_tasks table created successfully' AS result;
